[package]
name = "totp"
version = "0.1.0"
authors = ["Dr. Christian Geuer-Pollmann <chgeuer@microsoft.com>"]
edition = "2018"

[dependencies]
json = "*"
base32 = "0.4.0"
oath = "0.10.2"
clipboard-win = "2.2.0"
